openapi: 3.0.0

info:
  description: 'This is the domain for definitions of COBIS ADMIN module. This include, users, references, catalogs, etc.'
  version: '1.0.0'
  title: 'COBIS Admin Domain'

components:
  ####################################################################
  # Reusable schemas (data models)
  ####################################################################
  schemas:
    # OBJECTS
    Branch: # table:cl_oficina
      description: 'Oficina'
      properties:
        code: # field:of_oficina
          type: integer
          minimum: 1
          maximum: 32767
        name: # field:of_nombre
          type: string
          minLength: 1
          maxLength: 64
        #  of_filial
        #  of_direccion
        #  of_ciudad
        #  of_telefono
        #  of_subtipo
        #  of_area
        #  a_sucursal
        #  of_regional
        #  of_tip_punt_at
        #  of_cir_comunic
        #  of_nomb_encarg
        #  of_ci_encarg
        #  of_horario
        #  of_tipo_horar
        #  of_jefe_agenc
        #  of_cod_fie_asf
        #  of_fec_aut_asf
        #  of_sector
        #  of_depart_pais
        #  of_provincia
        #  of_barrio
        #  of_relac_ofic
        #  of_lat_coord
        #  of_lat_grad
        #  of_lat_min
        #  of_lat_seg
        #  of_long_coord
        #  of_long_grad
        #  of_long_min
        #  of_long_seg
        #  of_subregional
        #  of_obs_horario
        #  of_sucursal
        #  of_zona
        #  of_cob
        #  of_bloqueada
    
    City: # table:cl_ciudad
      description: 'Cuidad'
      properties:
        code: #  field:ci_ciudad
          type: number
          format: int32
          minimum: 1
        name: #  field:ci_descripcion
          type: string
          minLength: 1
          maxLength: 64
        status: #  field:ci_estado
          type: string # TODO: Validar catálogo 
          minLength: 1
          maxLength: 1
        #  ci_provincia
        #  ci_cod_remesas
        country: #  ci_pais
          $ref: '#/components/schemas/Country'
        #  ci_canton
    
    Country: # table:cl_pais
      description: 'Pais'
      properties:
        code: # field:pa_pais
          type: number
          format: int32
          minimum: 1
        name: # field:pa_descripcion
          type: string
          minLength: 1
          maxLength: 64
        isoCode: # field:pa_abreviatura
          type: string
          minLength: 1
          maxLength: 3
        # pa_continente
        # pa_nacionalidad
        status: # field:pa_estado
          type: string
          minLength: 1
          maxLength: 1
    
    Currency: # table:cl_moneda
      description: 'Moneda'
      properties:
        code: # field:mo_moneda
          type: integer
          minimum: 1
          maximum: 32767
        description: # field:mo_descripcion
          type: string
          minLength: 1
          maxLength: 64
        isoCode: # field:mo_nemonico
          type: string
          minLength: 3
          maxLength: 3
        symbol: # field:mo_simbolo
          type: string
          minLength: 1
          maxLength: 5
        country: # field:mo_pais
          $ref: '#/components/schemas/Country'
        # mo_decimales
        status: # field:mo_estado TODO: Validar catálogo cobis..cl_estado_ser??
          description: >
            'Estado de la moneda:'
              * V: Vigente
              * B: Bloqueado
              * E: Eliminado 
          type: string
          enum: [V,B,E]
          minLength: 1
          maxLength: 1
    
    Department: # table: cobis..cl_departamento
      description: 'Departamento de la organización.'
      properties:
        code: # field:de_departamento
          type: integer
          format: int32
          minimum: 0
          maximum: 32767
        name: # field:de_descripcion
          type: string
          minLength: 1
          maxLength: 64
        subsidiary: # field:de_filial -> cobis..cl_filial
          $ref: '#/components/schemas/Subsidiary'
        branch: # field:de_oficina
          $ref: '#/components/schemas/Branch'
        #de_o_oficina
        #de_o_departamento
        #de_nivel
    
    Officer: # table:cl_funcionario
      description: 'Funcionario o responsable de un usuario del sistema.'
      properties:
        code: # field:fu_funcionario
          type: integer
          format: int32
          minimum: 0
          maximum: 32767
        name: # field:fu_nombre
          type: string
          minLength: 1
          maxLength: 64
        Gender: # field:fu_sexo
          $ref: '#/components/schemas/Gender'
        # fu_dinero
        # fu_nomina
        # fu_departamento
        branch: # field:fu_oficina
          $ref: '#/components/schemas/Branch'
        # fu_cargo
        # fu_secuencial
        # fu_jefe
        # fu_nivel
        creationDate: # field:fu_fecha_ing
          type: string
          format: date
        user: # field:us_login -> cobis..ad_usuario
          $ref: '#/components/schemas/UserLogin'
        # fu_telefono
        # fu_fec_inicio
        # fu_fec_final
        # fu_clave
        # fu_estado
        # fu_offset
        identification: #fu_cedruc -> 
          $ref: '#/components/schemas/Identification'
        # fu_causa_bloqueo
        # fu_fecha_cargo
    
    User: # table:ad_usuario
      description: 'Usuario'
      properties:
        subsidiary: # field:us_filial
          $ref: '#/components/schemas/Subsidiary'
        branch: # field:us_oficina
          $ref: '#/components/schemas/Branch'
        #us_nodo
        login: # field:us_login
          $ref: '#/components/schemas/UserLogin'
        assignmentDate: # filed:us_fecha_asig
          type: string
          format: date
        # us_creador
        lastUpdateDate: # filed:us_fecha_ult_mod
          type: string
          format: date
        lastUpdatePasswordDate: # filed:us_fecha_ult_pwd
          type: string
          format: date
        status: # field: us_estado
          type: string
          minLength: 1
          maxLength: 1
    
    
    Identification: # virtual object
      description: 'Identificación de un cliente.'
      properties:
        number:
          $ref: '#/components/schemas/IdentificationNumber'
        type:
          $ref: '#/components/schemas/IdentificationType'
        birthCity:
          $ref: '#/components/schemas/City'
        issueDate:
          type: string
          format: date
    
    IdentificationType: # table:cobis..cl_tipo_documento
      description: 'Tipo de identificación de una persona natural o jurídica.'
      properties:
        code: # field:td_codigo
          $ref: '#/components/schemas/IdentificationTypeCode'
        name: # field:td_descripcion
          type: string
          minLength: 3
          maxLength: 30
        status: # field:td_estado # TODO: Catálogo
          type: string
          minLength: 1
          maxLength: 1
        #td_secuencial
        #td_mascara
        #td_tipoper
        #td_provincia
        #td_aperrapida
        #td_bloquea
        #td_nacionalidad
        #td_digito
        #td_estado
        #td_desc_corta
        #td_compuesto
        #td_nro_compuesto
        #td_adicional
        #td_creacion
        #td_habilitado_mis
        #td_habilitado_usu
        #td_prefijo
        #td_subfijo
    
    Subsidiary: # table:cl_filial
      description: 'Filial'
      properties:
        code: # field:fi_filial
          type: integer
          minimum: 1
          maximum: 255
        name: # field:fi_nombre
          type: string
          minLength: 1
          maxLength: 64
        status: # field:fi_estado # TODO: Catálogo
          type: string
          minLength: 1
          maxLength: 1
        #  fi_direccion
        #  fi_actividad
        #  fi_abreviatura
        #  fi_rep_nombre
        #  fi_contador
        #  fi_ruc
        #  fi_cont_nivel

    # CATALOGS
    Gender: # cobis..cl_catalogo[table:4:cl_sexo]
      description: >
        'Género o sexo de la persona.'
      properties:
        code:
          description: 'Código del sexo de la persona. Ver listado en: [http://www.cobiscorp.com/api/catalogo#cl_sexo](http://www.cobiscorp.com/api/catalogo#cl_sexo).' # TODO: Actualizar enlace a documentación de catálogos dinámicos.
          type: string
          minLength: 1
          maxLength: 1
        description:
              $ref: '#/components/schemas/CatalogDescription'
        status:
          $ref: '#/components/schemas/CatalogStatus'
  
    MaritalStatus: # cobis..cl_catalogo[table:211:cl_ecivil]
      description: >
        'Estado civil de la persona.'
      properties:
        code:
          description: 'Código del estado civil de la persona. Ver listado en: [http://www.cobiscorp.com/api/catalogo#cl_ecivil](http://www.cobiscorp.com/api/catalogo#cl_ecivil).' # TODO: Actualizar enlace a documentación de catálogos dinámicos.
          type: string
          minLength: 1
          maxLength: 1
        description:
              $ref: '#/components/schemas/CatalogDescription'
        status:
          $ref: '#/components/schemas/CatalogStatus'

  # KEY ELEMENTS
    ChannelCode: # TODO: Validar implementación de objeto en BD.
      description: >
        'Canal transccional'
          * 1: Oficina
          * 2: Agilizador
          * 3: Internet
          * 4: ATM
          * 5: APP Móvil
      type: integer
      enum: [1,2,3,4,5]
    
#    CatalogCode: # cobis..cl_catalogo.codigo
#      description: 'Código de un elemento de un catálogo'
#      type: string
#      minLength: 1
#      maxLength: 10
      
    CatalogDescription: # cobis..cl_catalogo.descripcion
      description: 'Descripción de un elemento de un catálogo.'
      type: string
      minLength: 1
      maxLength: 64
    
    CatalogStatus: # cobis..cl_catalogo.estado
      description: 'Estado de un elemento de un catálogo.'
      type: string
      minLength: 1
      maxLength: 1
    
    
    
    IdentificationTypeCode: # cobis..cl_tipo_documento.td_codigo
      description: >
        'Tipo de identificación de una persona natural o jurídica. Ver listado en: [http://www.cobiscorp.com/api/tabla#cl_tipo_documento](http://www.cobiscorp.com/api/tabla#cl_tipo_documento).' # TODO: Actualizar enlace a documentación de catálogos dinámicos.
      properties:
        code: # field:td_codigo 
          type: string
          minLength: 1
          maxLength: 4
      
    
    IdentificationNumber: # cobis..cl_ente.en_ced_ruc # TODO: Revisar implementación en BD.
      description: 'Número de identificación de una persona natural o jurídica.'
      type: string
      minLength: 5
      maxLength: 16
    
    UserLogin: # cobis..ad_usuario.us_login
      description: 'Login de usuario en el sistema CORE. Los usuarios autorizados realizan y autorizan transacciones en  el sistema.'
      type: string
      minLength: 1
      maxLength: 30
    
    
    #########################
    #  GENERAL COMPONENTS   #
    #########################
    Amount:
      description: 'Valor monetario'
      type: string
      pattern: '[0-9]{1,16}(\.[0-9]{1,2})'
